"""Pre-loaded NGX (Nigerian Stock Exchange) ticker list with company names."""

# Full list of NGX-listed companies: {ticker: company_name}
ALL_TICKERS: dict[str, str] = {
    "AIRTELAFRI": "Airtel Africa Plc",
    "BUAFOODS": "BUA Foods PLC",
    "MTNN": "MTN Nigeria Communications PLC",
    "DANGCEM": "Dangote Cement Plc",
    "BUACEMENT": "BUA Cement Plc",
    "SEPLAT": "Seplat Energy Plc",
    "ARADEL": "Aradel Holdings Plc",
    "GTCO": "Guaranty Trust Holding Company Plc",
    "ZENITHBANK": "Zenith Bank Plc",
    "GEREGU": "Geregu Power Plc",
    "WAPCO": "Lafarge Africa Plc",
    "INTBREW": "International Breweries Plc",
    "NB": "Nigerian Breweries Plc",
    "TRANSPOWER": "Transcorp Power Plc",
    "FIRSTHOLDCO": "First HoldCo Plc",
    "PRESCO": "Presco Plc",
    "UBA": "United Bank for Africa Plc",
    "STANBIC": "Stanbic IBTC Holdings PLC",
    "TRANSCOHOT": "Transcorp Hotels Plc",
    "NESTLE": "Nestlé Nigeria Plc",
    "ETI": "Ecobank Transnational Incorporated",
    "ACCESSCORP": "Access Holdings Plc",
    "OKOMUOIL": "The Okomu Oil Palm Company Plc",
    "WEMABANK": "Wema Bank PLC",
    "FIDELITYBK": "Fidelity Bank Plc",
    "DANGSUGAR": "Dangote Sugar Refinery Plc",
    "GUINNESS": "Guinness Nigeria Plc",
    "OANDO": "Oando PLC",
    "TRANSCORP": "Transnational Corporation of Nigeria Plc",
    "FCMB": "FCMB Group Plc",
    "UNILEVER": "Unilever Nigeria Plc",
    "MECURE": "Mecure Industries PLC",
    "STERLINGNG": "Sterling Financial Holdings Company Plc",
    "JBERGER": "Julius Berger Nigeria Plc",
    "JAIZBANK": "Jaiz Bank Plc",
    "NASCON": "Nascon Allied Industries Plc",
    "UCAP": "United Capital Plc",
    "CUSTODIAN": "Custodian Investment Plc",
    "NAHCO": "Nigerian Aviation Handling Company Plc",
    "UACN": "UAC of Nigeria PLC",
    "BETAGLAS": "Beta Glass Plc",
    "NGXGROUP": "The Nigerian Exchange Group Plc",
    "PZ": "PZ Cussons Nigeria Plc",
    "TOTAL": "TotalEnergies Marketing Nigeria Plc",
    "SKYAVN": "Skyway Aviation Handling Company Plc",
    "HONYFLOUR": "Honeywell Flour Mills Plc",
    "NEM": "NEM Insurance Plc",
    "FIDSON": "Fidson Healthcare Plc",
    "CHAMPION": "Champion Breweries Plc",
    "AIICO": "AIICO Insurance Plc",
    "ETRANZACT": "eTranzact International Plc",
    "ABBEYBDS": "Abbey Mortgage Bank Plc",
    "VITAFOAM": "Vitafoam Nigeria Plc",
    "CADBURY": "Cadbury Nigeria Plc",
    "MANSARD": "AXA Mansard Insurance Plc",
    "CONOIL": "Conoil Plc",
    "UPDC": "UPDC Plc",
    "CORNERST": "Cornerstone Insurance Plc",
    "VFDGROUP": "VFD Group PLC",
    "MBENEFIT": "Mutual Benefits Assurance Plc",
    "WAPIC": "Coronation Insurance Plc",
    "MAYBAKER": "May & Baker Nigeria plc",
    "IKEJAHOTEL": "Ikeja Hotel Plc",
    "CAP": "Chemical and Allied Products Plc",
    "CWG": "CWG Plc",
    "ELLAHLAKES": "Ellah Lakes Plc",
    "AFRIPRUD": "Africa Prudential Plc",
    "NEIMETH": "Neimeth International Pharmaceuticals Plc",
    "CONHALLPLC": "Consolidated Hallmark Holdings Plc",
    "SOVRENINS": "Sovereign Trust Insurance Plc",
    "CHAMS": "Chams Holding Company Plc",
    "ETERNA": "Eterna Plc",
    "INFINITY": "Infinity Trust Mortgage Bank Plc",
    "NPFMCRFBK": "NPF Microfinance Bank Plc",
    "EUNISELL": "Eunisell Interlinked Plc",
    "JAPAULGOLD": "Japaul Gold & Ventures Plc",
    "VERITASKAP": "Veritas Kapital Assurance Plc",
    "LINKASSURE": "Linkage Assurance Plc",
    "SUNUASSUR": "Sunu Assurances Nigeria Plc",
    "CUTIX": "Cutix Plc",
    "LIVINGTRUST": "Livingtrust Mortgage Bank PLC",
    "FTNCOCOA": "FTN Cocoa Processors Plc",
    "IMG": "Industrial and Medical Gases Nigeria Plc",
    "LASACO": "LASACO Assurance Plc",
    "UNIVINSURE": "Universal Insurance Plc",
    "CAVERTON": "Caverton Offshore Support Group Plc",
    "CILEASING": "C & I Leasing Plc",
    "TANTALIZER": "Tantalizers PLC",
    "NCR": "NCR (Nigeria) Plc",
    "PRESTIGE": "Prestige Assurance Plc",
    "LIVESTOCK": "Livestock Feeds Plc",
    "UPDCREIT": "UPDC Real Estate Investment Trust",
    "SCOA": "SCOA Nigeria Plc",
    "BERGER": "Berger Paints Nigeria Plc",
    "REGALINS": "Regency Alliance Insurance Plc",
    "UNITYBNK": "Unity Bank Plc",
    "TIP": "The Initiates Plc",
    "ROYALEX": "Royal Exchange Plc",
    "REDSTAREX": "Red Star Express Plc",
    "DAARCOMM": "Daar Communications Plc",
    "MORISON": "Morison Industries Plc",
    "RTBRISCOE": "R.T Briscoe (Nigeria) Plc",
    "NNFM": "Northern Nigeria Flour Mills Plc",
    "ABCTRANS": "ABC Transport Plc",
    "HMCALL": "Haldane Mccall Plc",
    "UHOMREIT": "UH Real Estate Investment Trust",
    "GUINEAINS": "Guinea Insurance Plc",
    "LEGENDINT": "Legend Internet Plc",
    "MULTIVERSE": "Multiverse Mining and Exploration Plc",
    "DEAPCAP": "DEAP Capital Management & Trust Plc",
    "CHELLARAM": "Chellarams Plc",
    "MEYER": "Meyer Plc",
    "SFSREIT": "SFS Real Estate Investment Trust Fund",
    "LEARNAFRCA": "Learn Africa Plc",
    "OMATEK": "Omatek Ventures Plc",
    "MCNICHOLS": "McNichols PLC",
    "RONCHESS": "Ronchess Global Resources PLC",
    "ACADEMY": "Academy Press Plc",
    "TRIPPLEG": "Tripple Gee & Company Plc",
    "GOLDBREW": "Golden Guinea Breweries Plc",
    "NSLTECH": "Secure Electronic Technology Plc",
    "AUSTINLAZ": "Austin Laz & Company Plc",
    "INTENEGINS": "International Energy Insurance Plc",
    "STACO": "STACO Insurance Plc",
    "AFRINSURE": "African Alliance Insurance Plc",
    "ZICHIS": "Zichis Agro Allied Industries PLC",
    "ALEX": "Aluminium Extrusion Industries Plc",
    "UNIONDICON": "Union Dicon Salt Plc",
    "FTGINSURE": "Fortis Global Insurance Plc",
    "ENAMELWA": "Nigerian Enamelware PLC",
    "EKOCORP": "Ekocorp Plc",
    "JOHNHOLT": "John Holt Plc",
    "UPL": "University Press Plc",
    "MULTITREX": "Multi-Trex Integrated Foods Plc",
    "JULI": "Juli plc",
    "PREMPAINTS": "Premier Paints Plc",
    "TRANSEXPR": "Trans-Nationwide Express Plc",
    "AFROMEDIA": "Afromedia Plc",
    "DUNLOP": "DN Tyre & Rubber Plc",
    "THOMASWY": "Thomas Wyatt Nigeria Plc",
    "PHARMDEKO": "Pharma Deko Plc",
    "VANLEER": "Greif Nigeria Plc",
    "BAPLC": "Briclinks Africa Plc",
    "FLOURMILL": "Flour Mills of Nigeria Plc",
    "FBNH": "FBN Holdings Plc",
}

# Top 30 most-traded NGX stocks
TOP_30 = [
    "DANGCEM", "MTNN", "GTCO", "AIRTELAFRI", "ZENITHBANK",
    "ACCESSCORP", "UBA", "FBNH", "NESTLE", "BUACEMENT",
    "SEPLAT", "OANDO", "DANGSUGAR", "STANBIC", "TRANSCORP",
    "WAPCO", "GEREGU", "PRESCO", "BUAFOODS", "ARADEL",
    "FIDELITYBK", "FCMB", "GUINNESS", "NB", "CADBURY",
    "FLOURMILL", "CONOIL", "NAHCO", "CUSTODIAN", "ETI",
]


def search_tickers(query: str, limit: int = 10) -> list[dict[str, str]]:
    """Search tickers by ticker symbol or company name (case-insensitive)."""
    query = query.upper().strip()
    if not query:
        return []

    results = []
    # Exact ticker match first
    if query in ALL_TICKERS:
        results.append({"ticker": query, "name": ALL_TICKERS[query]})

    # Prefix match on ticker
    for ticker, name in ALL_TICKERS.items():
        if ticker.startswith(query) and ticker != query:
            results.append({"ticker": ticker, "name": name})

    # Substring match on ticker or company name
    for ticker, name in ALL_TICKERS.items():
        if ticker == query or ticker.startswith(query):
            continue  # Already added
        if query in ticker or query in name.upper():
            results.append({"ticker": ticker, "name": name})

    return results[:limit]
